//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OyuncakSatisEntities1 : DbContext
    {
        public OyuncakSatisEntities1()
            : base("name=OyuncakSatisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Educational> Educationals { get; set; }
        public virtual DbSet<EducationalToy> EducationalToys { get; set; }
        public virtual DbSet<Plush> Plushs { get; set; }
        public virtual DbSet<PlushToy> PlushToys { get; set; }
        public virtual DbSet<Puzzle> Puzzles { get; set; }
        public virtual DbSet<PuzzleToy> PuzzleToys { get; set; }
        public virtual DbSet<Science> Sciences { get; set; }
        public virtual DbSet<ScienceToy> ScienceToys { get; set; }
    }
}
